change-id = 102579

[llvm]
thin-lto = true
targets = "AArch64;ARM;X86;RISCV"
experimental-targets = ""
link-shared = true
clang = true
download-ci-llvm = false
version-suffix = ""

[llvm.build-config]
LLVM_VERSION_SUFFIX = ""
LLVM_ENABLE_ZSTD = "FORCE_ON"
LLVM_USE_STATIC_ZSTD = "TRUE"

[build]
docs = false
submodules = false
extended = true
tools = [
    "cargo",
    "src",
    "clippy",
    "rust-analyzer",
    "rustfmt",
    "rust-analyzer-proc-macro-srv",
]
optimized-compiler-builtins = false
cargo-native-static = true

[install]
prefix = "../out"
sysconfdir = "etc"

[rust]
channel = "nightly"
lld = true
llvm-tools = true
jemalloc = true
lto = "thin"
strip = true

[target.aarch64-apple-darwin]
llvm-has-rust-patches = false

[target.x86_64-apple-darwin]
llvm-has-rust-patches = false
