change-id = 102579

[llvm]
thin-lto = true
targets = "AArch64;ARM;X86"
experimental-targets = ""
link-shared = true
clang = true
download-ci-llvm = false

[build]
docs = false
submodules = false
extended = true
tools = [
    "cargo",
    "src",
    "clippy",
    "rust-analyzer",
    "rustfmt",
    "rust-analyzer-proc-macro-srv",
]
cargo-native-static = true

[install]
prefix = "../out"
sysconfdir = "etc"

[rust]
channel = "nightly"
lld = true
llvm-tools = true
use-lld = "self-contained"
lto = "thin"

[target.x86_64-unknown-linux-gnu]
llvm-has-rust-patches = false
cc = "clang-16"
cxx = "clang++-16"
linker = "clang-16"
