changelog-seen = 2

[llvm]
targets = "AArch64;ARM;X86"
experimental-targets = ""
clang = true
static-libstdcpp = true
ldflags = "-s -static-libgcc -static"
download-ci-llvm = false

[build]
docs = false
submodules = false
extended = true
tools = ["cargo", "src", "clippy", "rust-analyzer", "rustfmt"]
cargo-native-static = true

[install]
prefix = "../out"
sysconfdir = "etc"

[rust]
channel = "nightly"
lld = true
llvm-tools = true

[dist]
include-mingw-linker = false
